### ISSUE TITLE
python sample.py error.

### ISSUE THREAD

**Issue by cheney369** [Bigfishering/f5-tts-trtllm#9]
你好，打扰了。我按你的步骤走下来，在最后运行sample.py的时候出现了下面的错误，能否抽空指点下是什么原因？

```
root@ort_llm:/data/f5-tts-trtllm/example# python sample.py 
[TensorRT-LLM] TensorRT-LLM version: 0.15.0
[01/03/2025-03:16:47] [TRT-LLM] [I] Loading engine from ./engine_outputs/rank0.engine
[01/03/2025-03:16:47] [TRT] [I] Loaded engine size: 636 MiB
[01/03/2025-03:16:47] [TRT] [I] [MS] Running engine with multi stream info
[01/03/2025-03:16:47] [TRT] [I] [MS] Number of aux streams is 1
[01/03/2025-03:16:47] [TRT] [I] [MS] Number of total worker streams is 2
[01/03/2025-03:16:47] [TRT] [I] [MS] The main stream provided by execute/enqueue calls is the first worker stream
[01/03/2025-03:16:47] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +79, now: CPU 0, GPU 711 (MiB)
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.277 seconds.
Prefix dict has been built successfully.


Run F5-TTS preprocess.
Traceback (most recent call last):
  File "/data/f5-tts-trtllm/example/sample.py", line 399, in <module>
    main(args)
  File "/data/f5-tts-trtllm/example/sample.py", line 385, in main
    denoised = model.forward(noise.cuda(), cond.cuda(), cond_drop.cuda(), time_expand.cuda(), rope_cos.cuda(), rope_sin.cuda(),  delta_t.cuda())
  File "/data/f5-tts-trtllm/example/sample.py", line 293, in wrapper
    ret = func(self, *args, **kwargs)
  File "/data/f5-tts-trtllm/example/sample.py", line 313, in forward
    'noise': noise.to(input_type),
RuntimeError: CUDA error: invalid resource handle
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[01/03/2025-03:16:48] [TRT] [E] [graphContext.h::~MyelinGraphContext::84] Error Code 1: Myelin ([impl.cpp:unload_cuda:621] Error 709 destroying event '0x5bec44773530'.)
[ort_llm:2036 :0:2036] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xd1b)
```

**Comment by tobegit3hub** [comment]
We have resolved this issue. It is the issue about binding gpu and you should uncomment the following code.

```
CUASSERT(cudart.cudaSetDevice(local_rank))
```

BTW, change the gpu index for your environment.

```
self.device = torch.device(f'cuda:{5}')
```

**Comment by cheney369** [comment]
> We have resolved this issue. It is the issue about binding gpu and you should uncomment the following code.
> 
> ```
> CUASSERT(cudart.cudaSetDevice(local_rank))
> ```
> 
> BTW, change the gpu index for your environment.
> 
> ```
> self.device = torch.device(f'cuda:{5}')
> ```

Thank you! It is running successfully now. However, I have another question to consult. When the text input for generating audio is long, it triggers a shape overflow error. I tried modifying some parameters during the compilation of `trtllm-build`, such as `--max_input_len` and `--max_seq_len`, but the same error still occurs. Can you tell me how to solve this problem?

**Comment by cheney369** [comment]
@tobegit3hub error:

`Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.278 seconds.
Prefix dict has been built successfully.


Run F5-TTS preprocess.
[01/09/2025-03:26:30] [TRT] [E] IExecutionContext::setInputShape: Error Code 3: API Usage Error (Parameter check failed, condition: satisfyProfile. Set dimension [1,2051,100] for tensor noise does not satisfy any optimization profiles. Valid range for profile 0: [1,100,100]..[1,2000,100].)
Traceback (most recent call last):
  File "/data/f5-tts-trtllm/example/sample.py", line 398, in <module>
    main(args)
  File "/data/f5-tts-trtllm/example/sample.py", line 384, in main
    denoised = model.forward(noise.cuda(), cond.cuda(), cond_drop.cuda(), time_expand.cuda(), rope_cos.cuda(), rope_sin.cuda(),  delta_t.cuda())
  File "/data/f5-tts-trtllm/example/sample.py", line 293, in wrapper
    ret = func(self, *args, **kwargs)
  File "/data/f5-tts-trtllm/example/sample.py", line 322, in forward
    self.session.set_shapes(self.inputs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/session.py", line 168, in set_shapes
    raise ValueError(
ValueError: Couldn't assign noise with shape torch.Size([1, 2051, 100]), engine supports [min, opt, max] = [(1, 100, 100), (1, 1226, 100), (1, 2000, 100)]
`

**Comment by tobegit3hub** [comment]
We have the same issue and we will split the long text with seperator. However, it need more change to support the long input text.

@Bigfishering any suggestion for this issue?
